name: ZombieArrival
main: uk.co.domaincraft.minecraft.plugins.zombie_arrival.ZombieArrival
version: 2.7
api-version: 1.16
description: >
             A Bukkit plugin that emulates a Zombie Apocalypse!