name: ZombieArrival
main: uk.co.domaincraft.minecraft.plugins.zombie_arrival.ZombieArrival
version: 2.1026201801
api-version: 1.13
description: >
             A Bukkit plugin that emulates a Zombie Apocalypse!